const COMMANDS: &[&str] = &[
    "is_supported",
    "access_granted",
    "open_settings",
    "open_external",
    "google_sign_in",
    "drain_pending",
    "show_capture_prompt",
    "cancel_capture_prompt",
    "peek_pending_capture_actions",
    "ack_capture_actions",
    "notification_posting_allowed",
    "request_notification_permission",
    "set_capture_settings",
    "set_sync_config",
    "sync_outbox_put",
    "sync_outbox_remove",
    "drain_sync_results",
    "clear_sync_outbox",
    "peek_logs",
    "clear_logs",
    "secure_get",
    "secure_set",
    "secure_delete",
    "biometric_available",
    "biometric_authenticate",
    "set_widget_spending",
    "set_widget_theme",
    "take_deep_link",
    "take_auth_redirect",
    "register_listener",
    "remove_listener",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
