use utoipa::OpenApi;

use crate::health;
use crate::models::{
    Account, AccountWithBalance, AcknowledgeAlertsResponse, AnticipateInstallmentsRequest,
    AnticipateInstallmentsResponse, Budget, BudgetAlert, BudgetAlertListResponse,
    BudgetListResponse, BudgetSummaryItem, BudgetSummaryResponse, BudgetWithCategory, CardBill,
    CardOverview, Category, CategoryBreakdownItem, CategoryBreakdownResponse, CategorySummary,
    CreateAccountRequest, CreateBudgetRequest, CreateCardPurchaseRequest, CreateCategoryRequest,
    CreateInstallmentPlanRequest, CreateLedgerTransactionRequest, CreateLedgerTransactionResponse,
    CreateTransactionRequest, GenerateInstallmentsResponse, InstallmentPlan, InstallmentPlanDetail,
    InstallmentProgress, InstallmentTransaction, LedgerEntry, LedgerEntryRequest,
    LedgerTransaction, MigrationResponse, MonthlyReportItem, MonthlyReportResponse,
    PayCardBillRequest, PayCardBillResponse, PayInstallmentResponse, ReconciliationItem,
    ReconciliationUploadRequest, ReconciliationUploadResponse, StatementLine, SummaryResponse,
    SyncOpResult, SyncOperation, SyncPullRequest, SyncPullResponse, SyncPushRequest,
    SyncPushResponse, Transaction, TransactionListParams, TransactionListResponse, TrendPoint,
    TrendsResponse, UpdateAccountRequest, UpdateCategoryRequest, UpdateTransactionRequest,
};
use crate::routes::accounts;
use crate::routes::audit;
use crate::routes::auth::{self, LoginRequest, RefreshRequest, RegisterRequest};
use crate::routes::budgets;
use crate::routes::categories::{self, CategoryListParams};
use crate::routes::credit_cards;
use crate::routes::installments;
use crate::routes::ledger;
use crate::routes::receipts::{
    self, MergeProductsRequest, OcrRequest, PriceHistoryParams, ReceiptItemInput,
    SaveReceiptRequest, ScanRequest,
};
use crate::routes::reports;
use crate::routes::summary::{self, SummaryParams};
use crate::routes::sync;
use crate::routes::transactions;

/// Root OpenAPI document for the PudimFinance API.
///
/// Aggregates utoipa path/schema annotations from the backend handlers
/// and is used by both the Swagger UI at runtime and the `gen-openapi` binary.
#[derive(OpenApi)]
#[openapi(
    paths(
        health::health_handler,
        health::metrics_handler_doc,
        categories::list_categories,
        categories::get_category,
        categories::create_category,
        categories::update_category,
        categories::delete_category,
        transactions::list_transactions,
        transactions::create_transaction,
        transactions::get_transaction,
        transactions::update_transaction,
        transactions::delete_transaction,
        summary::get_summary,
        budgets::list_budgets,
        budgets::create_budget,
        budgets::budget_summary,
        budgets::delete_budget,
        budgets::list_budget_alerts,
        budgets::acknowledge_alert,
        budgets::acknowledge_all_alerts,
        reports::monthly_report,
        reports::category_breakdown,
        reports::trends,
        accounts::list_accounts,
        accounts::get_account,
        accounts::create_account,
        accounts::update_account,
        accounts::delete_account,
        credit_cards::list_credit_cards,
        credit_cards::get_credit_card,
        credit_cards::list_card_bills,
        credit_cards::create_card_purchase,
        credit_cards::pay_card_bill,
        credit_cards::anticipate_installments,
        ledger::create_ledger_transaction,
        ledger::list_ledger_transactions,
        ledger::migrate_single_to_double,
        ledger::reconcile,
        ledger::upload_reconciliation,
        ledger::reconciliation_history,
        auth::register,
        auth::login,
        auth::refresh,
        auth::me,
        audit::list_audit_events,
        receipts::scan,
        receipts::ocr,
        receipts::save_receipt,
        receipts::list_receipts,
        receipts::price_history,
        receipts::merge_products,
        installments::list_installment_plans,
        installments::create_installment_plan,
        installments::get_installment_plan,
        installments::delete_installment_plan,
        installments::generate_installments,
        installments::pay_installment,
        sync::pull,
        sync::push,
    ),
    components(schemas(
        health::HealthResponse,
        health::HealthError,
        RegisterRequest,
        LoginRequest,
        RefreshRequest,
        ScanRequest,
        OcrRequest,
        SaveReceiptRequest,
        ReceiptItemInput,
        MergeProductsRequest,
        PriceHistoryParams,
        Account,
        AccountWithBalance,
        CreateAccountRequest,
        UpdateAccountRequest,
        CardBill,
        CardOverview,
        CreateCardPurchaseRequest,
        PayCardBillRequest,
        PayCardBillResponse,
        AnticipateInstallmentsRequest,
        AnticipateInstallmentsResponse,
        CreateLedgerTransactionRequest,
        CreateLedgerTransactionResponse,
        LedgerEntry,
        LedgerEntryRequest,
        LedgerTransaction,
        MigrationResponse,
        ReconciliationItem,
        ReconciliationUploadRequest,
        ReconciliationUploadResponse,
        StatementLine,
        Category,
        CreateCategoryRequest,
        UpdateCategoryRequest,
        CategoryListParams,
        Transaction,
        CreateTransactionRequest,
        UpdateTransactionRequest,
        TransactionListParams,
        TransactionListResponse,
        SummaryResponse,
        CategorySummary,
        SummaryParams,
        Budget,
        CreateBudgetRequest,
        BudgetListResponse,
        BudgetWithCategory,
        BudgetSummaryItem,
        BudgetSummaryResponse,
        BudgetAlert,
        BudgetAlertListResponse,
        AcknowledgeAlertsResponse,
        MonthlyReportItem,
        MonthlyReportResponse,
        CategoryBreakdownItem,
        CategoryBreakdownResponse,
        TrendPoint,
        TrendsResponse,
        InstallmentPlan,
        InstallmentProgress,
        InstallmentTransaction,
        InstallmentPlanDetail,
        CreateInstallmentPlanRequest,
        GenerateInstallmentsResponse,
        PayInstallmentResponse,
        SyncPullRequest,
        SyncPullResponse,
        SyncOperation,
        SyncPushRequest,
        SyncOpResult,
        SyncPushResponse,
    )),
    info(
        title = "PudimFinance API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Personal finance application API. Immutable double-entry ledger, \
                       event sourcing, real-time reporting, receipt scanning and price tracking.",
    ),
    servers(
        (url = "http://localhost:3000", description = "Local development"),
    ),
    tags(
        (name = "Health", description = "Health check and observability endpoints"),
        (name = "Categories", description = "Transaction category management"),
        (name = "Transactions", description = "Income and expense tracking"),
        (name = "Summary", description = "Monthly income/expense/balance summaries"),
        (name = "Budgets", description = "Monthly budget limits and budget vs actual tracking"),
        (name = "Reports", description = "Monthly reports, category breakdowns, and trends"),
        (name = "Ledger", description = "Double-entry ledger, event sourcing, and reconciliation"),
        (name = "Credit Cards", description = "Credit card accounts, billing cycles (faturas), payments, and installment anticipation"),
        (name = "Auth", description = "User registration, login, token refresh, and profile"),
        (name = "Audit", description = "Admin-only audit event search"),
        (name = "Receipts", description = "Receipt scanning (NFC-e QR), price history, and product normalization"),
    ),
    // Empty security requirement documents the public API (satisfies `security-defined`).
    security(
        (),
    ),
)]
pub struct ApiDoc;
