import {
  Activity,
  Apple,
  Baby,
  Banknote,
  Bed,
  Beef,
  Beer,
  Bike,
  Bone,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Calculator,
  Car,
  Carrot,
  Church,
  Coffee,
  Coins,
  Contact,
  CreditCard,
  Croissant,
  Dog,
  Drill,
  Droplet,
  Dumbbell,
  Ear,
  Eye,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  Handshake,
  HardHat,
  Heart,
  Home,
  Hospital,
  IceCream,
  IdCard,
  KeyRound,
  Landmark,
  Laptop,
  Lightbulb,
  MapPin,
  Megaphone,
  Monitor,
  MoreHorizontal,
  Music,
  Navigation,
  NotebookPen,
  Package,
  Paintbrush,
  Palmtree,
  PawPrint,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlusCircle,
  Presentation,
  Printer,
  Receipt,
  Refrigerator,
  Repeat,
  Ruler,
  Salad,
  Sailboat,
  Sandwich,
  Scale,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Soup,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Syringe,
  Tag,
  Tent,
  Thermometer,
  Ticket,
  TrainFront,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Warehouse,
  WashingMachine,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import { cn } from '@/lib/utils';

/** Lucide component for every category icon identifier. */
export const CATEGORY_ICON_COMPONENTS: Record<string, LucideIcon> = {
  // Food & dining
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  coffee: Coffee,
  pizza: Pizza,
  sandwich: Sandwich,
  salad: Salad,
  soup: Soup,
  'ice-cream': IceCream,
  cake: Cake,
  croissant: Croissant,
  wine: Wine,
  beer: Beer,
  fish: Fish,
  beef: Beef,
  carrot: Carrot,
  apple: Apple,
  // Groceries & shopping
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  store: Store,
  package: Package,
  shirt: Shirt,
  gift: Gift,
  // Home & utilities
  home: Home,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  phone: Phone,
  lightbulb: Lightbulb,
  sofa: Sofa,
  bed: Bed,
  wrench: Wrench,
  hammer: Hammer,
  'hard-hat': HardHat,
  drill: Drill,
  ruler: Ruler,
  paintbrush: Paintbrush,
  'key-round': KeyRound,
  'trash-2': Trash2,
  'washing-machine': WashingMachine,
  refrigerator: Refrigerator,
  // Transport
  car: Car,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  fuel: Fuel,
  truck: Truck,
  plane: Plane,
  sailboat: Sailboat,
  'map-pin': MapPin,
  navigation: Navigation,
  // Health
  heart: Heart,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  thermometer: Thermometer,
  activity: Activity,
  brain: Brain,
  bone: Bone,
  eye: Eye,
  ear: Ear,
  hospital: Hospital,
  'hand-heart': HandHeart,
  // Work & business
  briefcase: Briefcase,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  calculator: Calculator,
  'building-2': Building2,
  'file-text': FileText,
  scale: Scale,
  'id-card': IdCard,
  contact: Contact,
  handshake: Handshake,
  presentation: Presentation,
  megaphone: Megaphone,
  warehouse: Warehouse,
  // Education
  book: Book,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  pencil: Pencil,
  'notebook-pen': NotebookPen,
  // Leisure
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  trophy: Trophy,
  dumbbell: Dumbbell,
  palmtree: Palmtree,
  tent: Tent,
  repeat: Repeat,
  sparkles: Sparkles,
  // Family & personal
  users: Users,
  baby: Baby,
  dog: Dog,
  'paw-print': PawPrint,
  church: Church,
  scissors: Scissors,
  // Finance
  'trending-up': TrendingUp,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  receipt: Receipt,
  shield: Shield,
  landmark: Landmark,
  'plus-circle': PlusCircle,
  // Other
  'more-horizontal': MoreHorizontal,
  star: Star,
  flag: Flag,
  tag: Tag,
  tv: Tv,
};

function resolveCategoryIcon(name?: string | null): LucideIcon {
  return (name && CATEGORY_ICON_COMPONENTS[name]) || Tag;
}

type CategoryIconProps = Omit<React.SVGProps<SVGSVGElement>, 'name'> & {
  name?: string | null;
};

export function CategoryIcon({ name, className, ...props }: CategoryIconProps) {
  const Icon = resolveCategoryIcon(name);
  return <Icon aria-hidden="true" className={cn('h-4 w-4 shrink-0', className)} {...props} />;
}