//! Endpoints for registration, login, token refresh, and the current user.

#![allow(clippy::result_large_err)]

use axum::extract::State;
use axum::http::StatusCode;
use axum::{Json, Router};
use serde::Deserialize;
use serde_json::json;
use tracing::{error, info};
use uuid::Uuid;

use crate::auth;
use crate::state::AppState;

/// Request body for registering a new user.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct RegisterRequest {
    /// User email (must be unique).
    pub email: String,
    /// Plaintext password (hashed with Argon2id).
    pub password: String,
    /// Optional display name.
    pub display_name: Option<String>,
}

/// Request body for logging in.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct LoginRequest {
    /// User email.
    pub email: String,
    /// Plaintext password.
    pub password: String,
}

/// Request body for refreshing an access token.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct RefreshRequest {
    /// Refresh token issued at login.
    pub refresh_token: String,
}

/// Request body for completing a Google sign-in.
///
/// Desktop uses the authorization-code fields. Android uses an ID token from
/// Credential Manager and the nonce that was bound to that token.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct GoogleAuthRequest {
    /// ID token returned by Android Credential Manager.
    pub id_token: Option<String>,
    /// Nonce generated by the client and included in the native ID token.
    pub nonce: Option<String>,
    /// Authorization code returned by Google for the desktop flow.
    pub code: Option<String>,
    /// PKCE verifier generated by the desktop client.
    pub code_verifier: Option<String>,
    /// Redirect URI used in the desktop authorization request.
    pub redirect_uri: Option<String>,
    /// Public OAuth client ID used for the desktop authorization request.
    pub client_id: Option<String>,
}

#[derive(Debug)]
enum GoogleCredential<'a> {
    IdToken {
        token: &'a str,
        nonce: &'a str,
    },
    AuthorizationCode {
        code: &'a str,
        code_verifier: &'a str,
        redirect_uri: &'a str,
        client_id: &'a str,
    },
}

impl GoogleAuthRequest {
    fn credential(&self) -> Result<GoogleCredential<'_>, &'static str> {
        if let Some(token) = self.id_token.as_deref() {
            let Some(nonce) = self.nonce.as_deref() else {
                return Err("An ID token nonce is required");
            };
            if token.is_empty() || nonce.is_empty() {
                return Err("A non-empty ID token and nonce are required");
            }
            if self.code.is_some()
                || self.code_verifier.is_some()
                || self.redirect_uri.is_some()
                || self.client_id.is_some()
            {
                return Err("ID-token and authorization-code fields cannot be mixed");
            }
            return Ok(GoogleCredential::IdToken { token, nonce });
        }

        if self.nonce.is_some() {
            return Err("A nonce is only valid with an ID token");
        }
        match (
            self.code.as_deref(),
            self.code_verifier.as_deref(),
            self.redirect_uri.as_deref(),
            self.client_id.as_deref(),
        ) {
            (Some(code), Some(code_verifier), Some(redirect_uri), Some(client_id))
                if !code.is_empty()
                    && !code_verifier.is_empty()
                    && !redirect_uri.is_empty()
                    && !client_id.is_empty() =>
            {
                Ok(GoogleCredential::AuthorizationCode {
                    code,
                    code_verifier,
                    redirect_uri,
                    client_id,
                })
            }
            _ => Err("A complete Google authorization-code or ID-token payload is required"),
        }
    }
}

/// Auth sub-router.
pub fn router() -> Router<AppState> {
    Router::new()
        .route("/api/auth/register", axum::routing::post(register))
        .route("/api/auth/login", axum::routing::post(login))
        .route("/api/auth/google", axum::routing::post(google_login))
        .route("/api/auth/providers", axum::routing::get(providers))
        .route("/api/auth/refresh", axum::routing::post(refresh))
        .route("/api/auth/me", axum::routing::get(me))
}

/// Registers a new user.
#[utoipa::path(
    post,
    path = "/api/auth/register",
    tag = "Auth",
    request_body = RegisterRequest,
    responses(
        (status = 201, description = "User registered"),
        (status = 400, description = "Invalid registration payload"),
        (status = 409, description = "Email already registered"),
    ),
)]
pub async fn register(
    State(state): State<AppState>,
    Json(payload): Json<RegisterRequest>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let email = payload.email.trim().to_lowercase();
    if email.is_empty() || !email.contains('@') {
        return Err((
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "A valid email is required" })),
        ));
    }
    if payload.password.len() < 8 {
        return Err((
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "Password must be at least 8 characters" })),
        ));
    }

    let password_hash = auth::hash_password(&payload.password).map_err(|e| {
        error!("Failed to hash password: {}", e);
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "Failed to register user" })),
        )
    })?;

    let user_id = Uuid::new_v4();
    let insert = sqlx::query(
        "INSERT INTO users (id, email, password_hash, display_name, role)
         VALUES ($1, $2, $3, $4, 'user')",
    )
    .bind(user_id)
    .bind(&email)
    .bind(&password_hash)
    .bind(&payload.display_name)
    .execute(&state.pg_pool)
    .await;

    match insert {
        Ok(_) => {
            let access = auth::create_token(
                &state.jwt_secret,
                user_id,
                &email,
                "user",
                auth::ACCESS_TOKEN_TTL_SECS,
            )
            .map_err(|_| {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "token" })),
                )
            })?;
            let refresh = auth::create_token(
                &state.jwt_secret,
                user_id,
                &email,
                "user",
                auth::REFRESH_TOKEN_TTL_SECS,
            )
            .map_err(|_| {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "refresh" })),
                )
            })?;
            info!("Registered user {}", email);
            Ok(Json(json!({
                "access_token": access,
                "refresh_token": refresh,
                "token_type": "Bearer",
                "expires_in": auth::ACCESS_TOKEN_TTL_SECS,
                "user": { "id": user_id, "email": email, "role": "user" },
            })))
        }
        Err(e) => {
            if e.to_string().contains("duplicate key") {
                return Err((
                    StatusCode::CONFLICT,
                    Json(json!({ "error": "Email already registered" })),
                ));
            }
            error!("Failed to insert user: {}", e);
            Err((
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Failed to register user" })),
            ))
        }
    }
}

/// Logs a user in and returns tokens.
#[utoipa::path(
    post,
    path = "/api/auth/login",
    tag = "Auth",
    request_body = LoginRequest,
    responses(
        (status = 200, description = "Login successful"),
        (status = 401, description = "Invalid credentials"),
    ),
)]
pub async fn login(
    State(state): State<AppState>,
    Json(payload): Json<LoginRequest>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let email = payload.email.trim().to_lowercase();

    #[derive(sqlx::FromRow)]
    struct UserRow {
        id: Uuid,
        password_hash: Option<String>,
        role: String,
    }

    let row: Option<UserRow> =
        sqlx::query_as("SELECT id, password_hash, role FROM users WHERE email = $1")
            .bind(&email)
            .fetch_optional(&state.pg_pool)
            .await
            .map_err(|_| {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "auth fail" })),
                )
            })?;

    let user = row.ok_or((
        StatusCode::UNAUTHORIZED,
        Json(json!({ "error": "Invalid email or password" })),
    ))?;

    let Some(password_hash) = user.password_hash.as_deref() else {
        return Err((
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "This account signs in with Google" })),
        ));
    };

    let valid = auth::verify_password(&payload.password, password_hash).unwrap_or(false);
    if !valid {
        return Err((
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Invalid email or password" })),
        ));
    }

    let access = auth::create_token(
        &state.jwt_secret,
        user.id,
        &email,
        &user.role,
        auth::ACCESS_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "token" })),
        )
    })?;
    let refresh = auth::create_token(
        &state.jwt_secret,
        user.id,
        &email,
        &user.role,
        auth::REFRESH_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "refresh" })),
        )
    })?;

    Ok(Json(json!({
        "access_token": access,
        "refresh_token": refresh,
        "token_type": "Bearer",
        "expires_in": auth::ACCESS_TOKEN_TTL_SECS,
        "user": { "id": user.id, "email": email, "role": user.role },
    })))
}

/// Returns whether the server has Google sign-in configured.
#[utoipa::path(
    get,
    path = "/api/auth/providers",
    tag = "Auth",
    responses(
        (status = 200, description = "Available authentication providers"),
        (status = 429, description = "Too many requests"),
    ),
)]
pub async fn providers(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    Ok(Json(json!({ "google": state.google.is_some() })))
}

/// Completes Google OAuth, provisions or links the user, and returns Pudim tokens.
#[utoipa::path(
    post,
    path = "/api/auth/google",
    tag = "Auth",
    request_body = GoogleAuthRequest,
    responses(
        (status = 200, description = "Google login successful"),
        (status = 401, description = "Invalid Google authorization"),
        (status = 409, description = "Google account conflicts with an existing identity"),
        (status = 503, description = "Google sign-in is not configured"),
    ),
)]
pub async fn google_login(
    State(state): State<AppState>,
    Json(payload): Json<GoogleAuthRequest>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let Some(verifier) = state.google.as_ref() else {
        return Err((
            StatusCode::SERVICE_UNAVAILABLE,
            Json(json!({ "error": "Google sign-in is not configured" })),
        ));
    };
    let (id_token, expected_nonce, expected_audience) = match payload.credential() {
        Ok(GoogleCredential::IdToken { token, nonce }) => (token.to_owned(), Some(nonce), None),
        Ok(GoogleCredential::AuthorizationCode {
            code,
            code_verifier,
            redirect_uri,
            client_id,
        }) => {
            if !verifier.client_ids().iter().any(|id| id == client_id)
                || !valid_google_redirect(redirect_uri, client_id)
            {
                return Err((
                    StatusCode::BAD_REQUEST,
                    Json(json!({ "error": "Invalid Google OAuth client or redirect URI" })),
                ));
            }
            (
                verifier
                    .exchange_code(code, code_verifier, redirect_uri, client_id)
                    .await
                    .map_err(|error| {
                        error!("Google authorization-code exchange failed: {error:#}");
                        (
                            StatusCode::UNAUTHORIZED,
                            Json(json!({ "error": "Google authorization failed" })),
                        )
                    })?,
                None,
                Some(client_id.to_owned()),
            )
        }
        Err(message) => {
            return Err((StatusCode::BAD_REQUEST, Json(json!({ "error": message }))));
        }
    };
    let claims = verifier.verify_id_token(&id_token).await.map_err(|error| {
        error!("Google ID-token verification failed: {error:#}");
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Invalid Google identity token" })),
        )
    })?;
    if expected_nonce.is_some_and(|nonce| claims.nonce.as_deref() != Some(nonce)) {
        return Err((
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Google token nonce mismatch" })),
        ));
    }
    if expected_audience
        .as_deref()
        .is_some_and(|audience| claims.aud != audience)
    {
        return Err((
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Google token audience mismatch" })),
        ));
    }

    let email = claims.email.trim().to_lowercase();
    let mut transaction = state.pg_pool.begin().await.map_err(|error| {
        error!("Failed to start Google account transaction: {error}");
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "Failed to sign in" })),
        )
    })?;

    #[derive(sqlx::FromRow)]
    struct UserRow {
        id: Uuid,
        email: String,
        role: String,
        google_sub: Option<String>,
    }

    let by_sub: Option<UserRow> = sqlx::query_as(
        "SELECT id, email, role, google_sub FROM users WHERE google_sub = $1 FOR UPDATE",
    )
    .bind(&claims.sub)
    .fetch_optional(&mut *transaction)
    .await
    .map_err(|error| {
        error!("Failed to find Google identity: {error}");
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "Failed to sign in" })),
        )
    })?;

    let user = if let Some(user) = by_sub {
        if user.email != email {
            return Err((
                StatusCode::CONFLICT,
                Json(json!({ "error": "Google identity is linked to another email" })),
            ));
        }
        user
    } else {
        let by_email: Option<UserRow> = sqlx::query_as(
            "SELECT id, email, role, google_sub FROM users WHERE email = $1 FOR UPDATE",
        )
        .bind(&email)
        .fetch_optional(&mut *transaction)
        .await
        .map_err(|error| {
            error!("Failed to find email identity: {error}");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "Failed to sign in" })),
            )
        })?;

        if let Some(user) = by_email {
            if user.google_sub.is_some() {
                return Err((
                    StatusCode::CONFLICT,
                    Json(json!({ "error": "Email is linked to another Google identity" })),
                ));
            }
            sqlx::query("UPDATE users SET google_sub = $1, display_name = COALESCE(display_name, $2) WHERE id = $3")
                .bind(&claims.sub)
                .bind(&claims.name)
                .bind(user.id)
                .execute(&mut *transaction)
                .await
                .map_err(|error| {
                    error!("Failed to link Google identity: {error}");
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({ "error": "Failed to sign in" })),
                    )
                })?;
            UserRow {
                google_sub: Some(claims.sub.clone()),
                ..user
            }
        } else {
            let id = Uuid::new_v4();
            sqlx::query("INSERT INTO users (id, email, password_hash, display_name, google_sub, role) VALUES ($1, $2, NULL, $3, $4, 'user')")
                .bind(id)
                .bind(&email)
                .bind(&claims.name)
                .bind(&claims.sub)
                .execute(&mut *transaction)
                .await
                .map_err(|error| {
                    if error.to_string().contains("duplicate") {
                        return (
                            StatusCode::CONFLICT,
                            Json(json!({ "error": "Google identity is already linked" })),
                        );
                    }
                    error!("Failed to create Google user: {error}");
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({ "error": "Failed to sign in" })),
                    )
                })?;
            UserRow {
                id,
                email: email.clone(),
                role: "user".to_string(),
                google_sub: Some(claims.sub.clone()),
            }
        }
    };

    transaction.commit().await.map_err(|error| {
        error!("Failed to commit Google account transaction: {error}");
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "Failed to sign in" })),
        )
    })?;

    let access = auth::create_token(
        &state.jwt_secret,
        user.id,
        &user.email,
        &user.role,
        auth::ACCESS_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "token" })),
        )
    })?;
    let refresh = auth::create_token(
        &state.jwt_secret,
        user.id,
        &user.email,
        &user.role,
        auth::REFRESH_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "refresh" })),
        )
    })?;

    info!("Google user signed in {}", user.email);
    Ok(Json(json!({
        "access_token": access,
        "refresh_token": refresh,
        "token_type": "Bearer",
        "expires_in": auth::ACCESS_TOKEN_TTL_SECS,
        "user": { "id": user.id, "email": user.email, "role": user.role },
    })))
}

fn valid_google_redirect(redirect_uri: &str, client_id: &str) -> bool {
    if redirect_uri
        == format!(
            "com.googleusercontent.apps.{}:/oauth2redirect",
            client_id.trim_end_matches(".apps.googleusercontent.com")
        )
    {
        return true;
    }
    redirect_uri
        .strip_prefix("http://")
        .and_then(|value| value.split_once('/'))
        .is_some_and(|(authority, path)| {
            let Some((host, port)) = authority.rsplit_once(':') else {
                return false;
            };
            (host == "127.0.0.1" || host == "localhost")
                && port.parse::<u16>().is_ok_and(|port| port != 0)
                && path == "oauth2redirect"
        })
}

#[cfg(test)]
mod tests {
    use super::{GoogleAuthRequest, GoogleCredential};

    fn code_request() -> GoogleAuthRequest {
        GoogleAuthRequest {
            id_token: None,
            nonce: None,
            code: Some("code".to_string()),
            code_verifier: Some("verifier".to_string()),
            redirect_uri: Some("redirect".to_string()),
            client_id: Some("client".to_string()),
        }
    }

    #[test]
    fn accepts_a_complete_authorization_code_payload() {
        assert!(matches!(
            code_request().credential(),
            Ok(GoogleCredential::AuthorizationCode { .. })
        ));
    }

    #[test]
    fn accepts_an_id_token_payload_with_nonce() {
        let request = GoogleAuthRequest {
            id_token: Some("token".to_string()),
            nonce: Some("nonce".to_string()),
            code: None,
            code_verifier: None,
            redirect_uri: None,
            client_id: None,
        };
        assert!(matches!(
            request.credential(),
            Ok(GoogleCredential::IdToken { .. })
        ));
    }

    #[test]
    fn rejects_incomplete_or_mixed_payloads() {
        let mut incomplete = code_request();
        incomplete.client_id = None;
        assert!(incomplete.credential().is_err());

        let mut mixed = code_request();
        mixed.id_token = Some("token".to_string());
        mixed.nonce = Some("nonce".to_string());
        assert!(mixed.credential().is_err());
    }
}

/// Refreshes tokens.
#[utoipa::path(
    post,
    path = "/api/auth/refresh",
    tag = "Auth",
    request_body = RefreshRequest,
    responses(
        (status = 200, description = "Tokens refreshed"),
        (status = 401, description = "Invalid or expired refresh token"),
    ),
)]
pub async fn refresh(
    State(state): State<AppState>,
    Json(payload): Json<RefreshRequest>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let claims = auth::verify_token(&state.jwt_secret, &payload.refresh_token).map_err(|_| {
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Invalid or expired refresh token" })),
        )
    })?;

    let user_id = Uuid::parse_str(&claims.sub).map_err(|_| {
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Invalid token subject" })),
        )
    })?;

    let access = auth::create_token(
        &state.jwt_secret,
        user_id,
        &claims.email,
        &claims.role,
        auth::ACCESS_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "token" })),
        )
    })?;
    let refresh = auth::create_token(
        &state.jwt_secret,
        user_id,
        &claims.email,
        &claims.role,
        auth::REFRESH_TOKEN_TTL_SECS,
    )
    .map_err(|_| {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": "refresh" })),
        )
    })?;

    Ok(Json(json!({
        "access_token": access,
        "refresh_token": refresh,
        "token_type": "Bearer",
        "expires_in": auth::ACCESS_TOKEN_TTL_SECS,
        "user": { "id": user_id, "email": claims.email, "role": claims.role },
    })))
}

/// Returns current user info from Bearer token.
#[utoipa::path(
    get,
    path = "/api/auth/me",
    tag = "Auth",
    responses(
        (status = 200, description = "Current user"),
        (status = 401, description = "Not authenticated"),
    ),
)]
pub async fn me(
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let token = headers
        .get("authorization")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .ok_or_else(|| {
            (
                StatusCode::UNAUTHORIZED,
                Json(json!({ "error": "Missing Bearer" })),
            )
        })?;

    let claims = auth::verify_token(&state.jwt_secret, token).map_err(|_| {
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({ "error": "Invalid or expired token" })),
        )
    })?;

    Ok(Json(json!({
        "id": claims.sub,
        "email": claims.email,
        "role": claims.role,
    })))
}
