#!/usr/bin/env python3
"""Make the CI-generated Tauri Android project produce a *signed* release APK.

`desktop/src-tauri/gen/` is gitignored and re-created on every CI run by
`tauri android init`, so the Gradle signing configuration documented at
<https://v2.tauri.app/distribute/sign/android/> cannot be committed. This
script therefore runs between `tauri android init` and `tauri android build`:

1. when the keystore secret is set, it decodes it and writes
   `gen/android/keystore.properties` (alias, passwords, absolute store path);
2. it injects the matching `signingConfigs`/`signingConfig` Kotlin into
   `gen/android/app/build.gradle.kts`. The release build type falls back to the
   debug keystore when `keystore.properties` is absent, so a build without the
   secret still yields an installable (debug-signed) APK instead of an
   unsigned one.

Accepted secret names (first one set wins, so the legacy Expo secrets keep
working):

- keystore: ``ANDROID_KEYSTORE_BASE64`` / ``ANDROID_KEY_BASE64`` / ``RELEASE_KEYSTORE_BASE64``
- alias: ``ANDROID_KEY_ALIAS`` / ``RELEASE_KEY_ALIAS``
- passwords: ``ANDROID_KEYSTORE_PASSWORD`` / ``ANDROID_KEY_PASSWORD`` /
  ``RELEASE_KEYSTORE_PASSWORD`` (and ``RELEASE_KEY_PASSWORD`` for the key) —
  ``keyPassword`` is only written when it differs from the keystore password.

Idempotent: safe to run more than once against the same project.
"""

from __future__ import annotations

import base64
import os
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
ANDROID_DIR = REPO_ROOT / "desktop" / "src-tauri" / "gen" / "android"
KEYSTORE_PROPERTIES = ANDROID_DIR / "keystore.properties"
GRADLE_FILE = ANDROID_DIR / "app" / "build.gradle.kts"

# Injected before the `buildTypes {` block (4-space indentation, re-indented to
# whatever the generated project uses).
SIGNING_CONFIGS = """\
    // Injected by scripts/android-signing.py (see tauri.app/distribute/sign/android).
    // Signs release builds with the upload keystore CI provides through
    // keystore.properties, falling back to the debug keystore so a build
    // without the secret is still installable (Play Protect may warn).
    signingConfigs {
        create("release") {
            val keystorePropertiesFile = rootProject.file("keystore.properties")
            if (keystorePropertiesFile.exists()) {
                val keystoreProperties = Properties()
                keystoreProperties.load(keystorePropertiesFile.inputStream())
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["password"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = (keystoreProperties["keyPassword"] ?: keystoreProperties["password"]) as String
            }
        }
    }
"""

SIGNING_CONFIG_LINE = (
    'signingConfig = if (rootProject.file("keystore.properties").exists()) '
    'signingConfigs.getByName("release") else signingConfigs.getByName("debug")'
)

PROPERTIES_IMPORT = "import java.util.Properties\n"
INJECTION_MARKER = "// Injected by scripts/android-signing.py"


def env(*names: str) -> str:
    """First non-empty value among ``names`` (later names are fallbacks)."""
    for name in names:
        value = os.environ.get(name, "").strip()
        if value:
            return value
    return ""


def configure_keystore() -> bool:
    """Write keystore.properties when a keystore secret is configured."""
    encoded = env("ANDROID_KEYSTORE_BASE64", "ANDROID_KEY_BASE64", "RELEASE_KEYSTORE_BASE64")
    if not encoded:
        return False

    alias = env("ANDROID_KEY_ALIAS", "RELEASE_KEY_ALIAS")
    store_password = env(
        "ANDROID_KEYSTORE_PASSWORD",
        "ANDROID_KEY_PASSWORD",
        "RELEASE_KEYSTORE_PASSWORD",
        "RELEASE_KEY_PASSWORD",
    )
    key_password = env(
        "ANDROID_KEY_PASSWORD",
        "RELEASE_KEY_PASSWORD",
        "ANDROID_KEYSTORE_PASSWORD",
        "RELEASE_KEYSTORE_PASSWORD",
    )
    if not alias or not store_password:
        sys.exit(
            "error: a keystore secret is set but ANDROID_KEY_ALIAS/"
            "ANDROID_KEYSTORE_PASSWORD are missing",
        )

    # The runner is ephemeral: keep the binary in RUNNER_TEMP, owner-only.
    keystore = pathlib.Path(os.environ.get("RUNNER_TEMP") or "/tmp") / "pudim-upload-keystore.jks"
    try:
        keystore.write_bytes(base64.b64decode(encoded, validate=True))
    except ValueError as exc:  # includes binascii.Error (invalid base64 / padding)
        sys.exit(f"error: ANDROID_KEYSTORE_BASE64 is not valid base64: {exc}")
    keystore.chmod(0o600)

    lines = [
        "# Generated by scripts/android-signing.py — never commit.",
        f"keyAlias={alias}",
        f"password={store_password}",
    ]
    if key_password != store_password:
        lines.append(f"keyPassword={key_password}")
    lines.append(f"storeFile={keystore}")
    KEYSTORE_PROPERTIES.write_text("\n".join(lines) + "\n")
    KEYSTORE_PROPERTIES.chmod(0o600)
    return True


def patch_gradle() -> None:
    """Inject the release signing config into the generated Gradle project."""
    if not GRADLE_FILE.is_file():
        sys.exit(f"error: {GRADLE_FILE} not found — run `npm run tauri android init` first")

    source = GRADLE_FILE.read_text()

    if INJECTION_MARKER in source:
        return  # already patched (idempotent)

    if "signingConfigs {" in source:
        sys.exit(
            f"error: {GRADLE_FILE} already declares signingConfigs — the tauri-cli "
            "template changed, review scripts/android-signing.py",
        )

    if PROPERTIES_IMPORT not in source:
        source = PROPERTIES_IMPORT + source

    build_types = re.search(r"^(\s*)buildTypes\s*\{", source, flags=re.MULTILINE)
    if not build_types:
        sys.exit(
            f"error: no `buildTypes {{` block in {GRADLE_FILE} "
            "— did the tauri-cli template change?",
        )
    indent = build_types.group(1)
    block = re.sub(r"^    ", indent, SIGNING_CONFIGS, flags=re.MULTILINE)
    source = source[: build_types.start()] + block + source[build_types.start() :]

    release = re.search(r'getByName\("release"\)\s*\{', source)
    if not release:
        sys.exit(
            f"error: no release build type in {GRADLE_FILE} "
            "— did the tauri-cli template change?",
        )
    line_start = source.rfind("\n", 0, release.start()) + 1
    base_indent = re.match(r"\s*", source[line_start : release.start()]).group(0)
    body_indent = base_indent + "    "
    source = (
        source[: release.end()]
        + "\n"
        + body_indent
        + SIGNING_CONFIG_LINE
        + source[release.end() :]
    )

    GRADLE_FILE.write_text(source)


def main() -> int:
    if not ANDROID_DIR.is_dir():
        sys.exit(f"error: {ANDROID_DIR} not found — run `npm run tauri android init` first")

    signed = configure_keystore()
    patch_gradle()

    if signed:
        print(f"Release signing configured from the CI keystore secrets ({KEYSTORE_PROPERTIES}).")
    else:
        print(
            "::warning::No keystore secret set (ANDROID_KEYSTORE_BASE64) — the release "
            "APK will be debug-signed and Google Play Protect may block the sideload.",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
